name: Build master

on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: "switch-library-manager.exe", platform: windows/amd64, os: windows-latest },
          { name: "switch-library-manager", platform: linux/amd64, os: ubuntu-latest },
          { name: "switch-library-manager", platform: darwin/universal, os: macos-latest }
        ]

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/upload-artifact@v3
        with:
          name: switch-library-manager.${{ matrix.build.platform }}
          path: src/output/${{ matrix.build.platform }}/*
          if-no-files-found: error
          
      - uses: dAppServer/wails-build-action@vmain
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
